{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- $envAll := . }}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dns-helper
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "dns" "helper" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
      - name: dns-helper
        image: {{ .Values.images.tags.dns_helper }}
        imagePullPolicy: {{ .Values.images.pull_policy }}
        command:
          - /tmp/dns-helper.sh
        volumeMounts:
          - mountPath: /host/etc/resolv.conf
            name: host-resolv-conf
          - name: dns-helper-bin
            mountPath: /tmp/dns-helper.sh
            subPath: dns-helper.sh
            readOnly: true
      volumes:
        - name: host-resolv-conf
          hostPath:
            path: /etc/resolv.conf
        - name: dns-helper-bin
          configMap:
            name: dns-helper-bin
            defaultMode: 0555
